name: CI/CD for Dockerized vlakvlog

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t my-docker-app .

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Push Docker image
        run: |
          docker tag my-docker-app "${{ secrets.DOCKERHUB_USERNAME }}/my-docker-app:${{ github.sha }}"
          docker push "${{ secrets.DOCKERHUB_USERNAME }}/my-docker-app:${{ github.sha }}"
